name: "My Shell Action"
description: "A GitHub Action that uses shell commands and sets an output value"
inputs:
  name:
    description: "Name to greet"
    required: true
    default: "World"
outputs:
  greeting:
    description: "The greeting message"
    value: ${{ steps.set-output.outputs.greeting }}  # Referencing the output value from a step    
runs:
  using: "composite"
  steps:
    - id: set-output  # Assign an ID to the step
      run: |
        echo "Hello, ${{ inputs.name }}!"
        # Create a greeting message
        GREETING="Hello, Miss ${{ inputs.name }}! Welcome to GitHub Workflow."
        # Set the output variable
        echo "greeting=$GREETING" >> $GITHUB_OUTPUT
      shell: bash  
